pipeline:
  name: terraform init
  identifier: terraform_init
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: clone-code
        identifier: clonecode
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: init-terraform
                  identifier: initterraform
                  spec:
                    shell: Sh
                    command: |-
                      echo hello
                      pwd
                      ls
              - step:
                  type: Run
                  name: terraform
                  identifier: terraform
                  spec:
                    shell: Bash
                    command: terraform init
        delegateSelectors:
          - delegate-1-terraform
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: ipreetgs/test-harness
        build: <+input>
