pipeline:
  name: terraform init
  identifier: terraform_init
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: terraform init
        identifier: terraform_init
        tags: {}
        template:
          templateRef: init_stage
          versionLabel: v1
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: ipreetgs/test-harness
        build: <+input>
