pipeline:
  name: terraform init
  identifier: terraform_init
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: ipreetgs/test-harness
        build: <+input>
  stages:
    - stage:
        name: terrafork
        identifier: terrafork
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: TerraformPlan_1
                  identifier: TerraformPlan_1
                  spec:
                    provisionerIdentifier: v1s1
                    cloudCliConfiguration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: awspersonal
                            bucketName: demotxtfstatefile
                            region: us-east-1
                            folderPath: /
                          type: S3
                      skipStateStorage: false
                    delegateSelectors:
                      - docker-delegate
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Abort
        tags: {}
        delegateSelectors:
          - docker-delegate
