pipeline:
  name: terraform init
  identifier: terraform_init
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: terraform-test
        identifier: terraformtest
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Bash
                    command: terraform init
        delegateSelectors:
          - docker-delegate2-terraform
          - delegate-1-terraform
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1702454216196
        repoName: ipreetgs/test-harness
        build: <+input>
