pipeline:
  name: terraform init
  identifier: terraform_init
  projectIdentifier: DemoTx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: terraform init
        identifier: terraform_init
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: TerraformPlan_1
                  identifier: TerraformPlan_1
                  spec:
                    provisionerIdentifier: a1a
                    cloudCliConfiguration:
                      command: Apply
                      configFiles:
                        store:
                          spec:
                            connectorRef: account.Github_OAuth_1702454216196
                            repoName: ipreetgs/test-harness
                            gitFetchType: Branch
                            branch: main
                            folderPath: .
                          type: Github
                        moduleSource:
                          useConnectorCredentials: true
                  timeout: 10m
        tags: {}
        delegateSelectors:
          - docker-delegate2-terraform
          - delegate-1-terraform
